config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated  do
      root to: 'groups#index'
   end
   unauthenticated do
    root to: 'home#index', as: 'unauthenticated_root'
end
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :home, only: [:index]
  resources :entities, only: [:new, :create, :destroy] do
    resources :relations, only: [:create]
  end
    resources :groups, only: [:index, :show, :new, :create, :destroy]
  # root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :relations, dependent: :destroy

  validates :name, presence: true
  validates :amount, numericality: { greater_than: 0 }

  def created_at
    attributes['created_at'].strftime('%d %b %Y')
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :relations, dependent: :destroy

  validates :icon, presence: true

  def created_at
    attributes['created_at'].strftime('%d %b %Y')
  end

  def self.total(id)
    group = Group.find(id)
    relations = group.relations
    @total = 0
    relations.each do |relation|
      entity = Entity.find(relation.entity_id)
      @total += entity.amount.to_i
    end
    @total
  end
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
  has_many :groups, dependent: :destroy
  has_many :entities, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def new
    @entity = current_user.entities.new
    @relation = Relation.new(entity: @entity)
  end

  def create
    entity = current_user.entities.new(entity_params)
    respond_to do |format|
      format.html do
        if entity.save
          relation = Relation.create(group_id: group_params, entity_id: entity.id)
          redirect_to group_path(relation.group_id)
        else
          render :new
        end
      end
    end
  end

  def destroy
    @entity = current_user.entities.find(params[:id])
    @entity.destroy
    redirect_to groups_path
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end

  def group_params
    params[:entity][:relation][:group_id]
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  def index
    @groups = current_user.groups.all
  end

  def show
    @group = Group.find(params[:id])
    @relations = @group.relations.order('created_at DESC')
  end

  def new
    @group = current_user.groups.new
  end

  def create
    group = current_user.groups.new(group_params)
    respond_to do |format|
      format.html do
        if group.save
          redirect_to groups_path
        else
          render :new
        end
      end 
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
      params.require(:group).permit(:name, :icon)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups.all
  end

  def show
    @group = Group.find(params[:id])
    @relations = @group.relations.order('created_at DESC')
  end

  def new
    @group = current_user.groups.new
  end

  def create
    group = current_user.groups.new(group_params)
    respond_to do |format|
      format.html do
        if group.save
          redirect_to groups_path
        else
          render :new
        end
      end
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/relation_controllers.rb
class RelationController < ActionController::Base
  def new
    @group = Group.all
    @entity = current_user.entities.new
    @relation = Relation.new
  end
end

app/controllers/relations_controller.rb
class RelationsController < ActionController::Base
  def new
    @group = Group.all
    @entity = current_user.entities.new
    @relation = Relation.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entities/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <section>
    <div>

    <h1>Add New Transaction</h1>

<%= form_with class: "new_user", model: @entity do |f| %>

  <div class="field">
      <%= f.label :name %>
      <br />
      <%= f.text_field :name, class: "input", required: true %>
  </div>

  <div class="field">
      <%= f.label :amount %>
      <br />
      <%= f.number_field :amount, class: "input", min: 1, required: true %>
  </div>

      <div class="field">
      <%= f.fields_for(@relation) do |r| %>
      <%= r.label :group%>
      <br />
      <%= r.select :group_id, current_user.groups.collect { |group| [group.name, group.id]}, {include_blank: true}, class: "input",required: true %>
     <% end %>   
    </div>

  <div>
      <%= f.submit %>
  </div>

<% end %>

    </div>
    </section>


  </body>
</html>

app/views/group/index.html.erb
<%
=begin%>
 <%= link_to 'Edit profile', edit_user_registration_path %> |
<%= link_to "Sign out", destroy_user_session_path, method: :get %> 
<%
=end%>
<%= render "partials/navbar" %>

<section>
    <%@groups.each do |group|%>
      <div>
        <img src=<%=group.icon%> alt="icon">

        <%= link_to group_path(group.id), :remote => true do %>
          <h3><%=group.name%></h3>
        <%end%>

        <p><%=group.created_at%></p>
          <h3>$<%=Group.total(group.id)%>.00</h3>
          <%= button_to "Delete", group_path(group.id), html: {'data-turbo' => "false"}, :method => :delete %>
      </div>
    <%end%>
</section>

<div>
  <%= link_to new_group_path,  :remote => true do %>
    <input type="button" value="Add Category">
  <% end %>
</div>

app/views/group/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section>
      <div>

        <h1>Add A New Category</h1>
        <%= form_with html: {'data-turbo' => "false"}, model: @groups do |f| %>

        <div>
          <%= f.label :name %>
          <%= f.text_field :name, required: true %>
        </div>

        <div>
          <%= f.label :icon %>
          <%= f.text_field :icon, required: true %>
        </div>

        <div>
          <%= f.submit "Create Category" %>
        </div>

      <% end %>
      <%= link_to '/', :remote => true do %>
        <input type="button" value="Back">
      <% end %> 
    </div>
  </section>
</body>
</html>

app/views/groups/index.html.erb
<%= render "partials/navbar" %>

<section>
    <%@groups.each do |group|%>
      <div class = "body-flex">
        <div class="img-cover align-self">
          <img src=<%=group.icon%> alt="icon">
        </div>
        <div class="name-cover">
          <%= link_to group_path(group.id), :remote => true do %>
            <h3 class="group-name"><%=group.name%></h3>
          <%end%>
        </div>
        <div>
          <h3 class="group-cover">$<%=Group.total(group.id)%>.00</h3> 
        </div>
        <div class="align-self">
          <p class="group-cover"><%=group.created_at%></p>
        </div>
        <div class="button-cover">
          <%= button_to "Delete", group_path(group.id), html: {'data-turbo' => "false"}, :method => :delete %>
        </div>
      </div>
    <%end%>
</section>

<div id="add-category-cover">
  <%= link_to new_group_path,  :remote => true do %>
    <input type="button" value="Add Category">
  <% end %>
</div>

app/views/groups/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section>
      <div>

        <h1>Add A New Category</h1>
        <%= form_with html: {'data-turbo' => "false"}, class: "new_user", model: @group do |f| %>

          <div class="field">
            <%= f.label :name %>
            <br />
            <%= f.text_field :name, class: "input", required: true %>
          </div>

          <div class="field">
            <%= f.label "add icon or image" %>
            <br />
            <%= f.text_field :icon, class: "input", required: true %>
          </div>

          <div>
            <%= f.submit "Create Category" %>
          </div>

        <% end %>
    </div>
    <div class="back-cover">
      <%= link_to '/', :remote => true do %>
        <input type="button" value="Back">
      <% end %> 
    </div>
  </section>
</body>
</html>

app/views/groups/show.html.erb
<%= render "partials/nav" %>
<div class="button-flex gift">
  <h1 class="coupons">Gift Coupons</h1>
  <h3 class="coupons">$<%=Group.total(@group.id)%>.00</h3>
</div>

<%@relations.each do |relation|%>
  <%entity = Entity.find(relation.entity_id)%>
  <div class = "body-flex">
    <img src=<%=@group.icon%> alt="icon">

    <h3 class="group-name"><%=entity.name%></h3>
    <h3 class="group-cover">$<%=entity.amount%>.00</h3>
    <p class="group-cover"><%=entity.created_at%></p>
    <div class="button-cover">
      <%= button_to "Delete", entity_path(entity.id), html: {'data-turbo' => "false"}, :method => :delete %>
    </div>
  </div>
<%end%>

<div class="button-flex">
<%= link_to new_entity_path, :remote => true do %>
  <input type="button" id="btn" value="Add transaction">
<% end %>
<br>

<%= link_to groups_path, :remote => true do %>
  <input type="button" value="Back">
<% end %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <section>
      <div>

        <h1>Budget App</h1>

        <%= link_to new_user_registration_path, :remote => true do  %>
          <input type="button" value="SIGN UP">
        <%end%>
        
        <%= link_to new_user_session_path, :remote => true do  %>
          <input type="button" value="LOGIN">
        <%end%>

      </div>

    </section>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav>
      <%= link_to groups_path, :remote => true do %>
        <i class="fa fa-arrow-left fa-lg" style="color:white"></i>
      <%end%>
      <a href="/groups" class="categories">Transactions</a>
      <%= link_to destroy_user_session_path, method: :get do %>
        <h3>Log Out</h3>
      <% end %>
    </nav>
  </body>
</html>

app/views/partials/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
    <div></div>
      <h1 class="categories">Categories</h1>
      <%= link_to destroy_user_session_path, method: :get do %>
        <h3>Log Out</h3>
      <% end %>
   </nav>


  </body>
</html>